claim:
  vertexpand: false
  blocklimits:
    enabled: false
    limits: {}
    minimal:
      volume: 0
      horizontal: 0
      vertical: 0
regionprotect:
  flow:
    lava: false
    water: false
    other: false
  fire:
    spread:
      toregion: false
      inregion: false
    burn: false
  explosion:
    block: false
    entity: false
autoflags:
  enabled: false
  show-messages: false
  flags: {}
restrictcommands:
  enabled: false
  commands: []
extendedwewand: false
misc:
  pvpmode: default
  old-pvp-flags: true

messages:
  # Форматирование текста
  # LEGACY - использует & коды
  # MINIMESSAGE - цвет через <цвет> (<green>, <bold> и т.д.)
  serializer: MINIMESSAGE
  player-only-command: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Эта команда доступна только игрокам."
  global-region-name-forbidden: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Нельзя заприватить регион с названием __global__."
  invalid-region-name: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Имя региона <red>%id%<gray> содержит запрещённые символы."
  max-claim-volume-error: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Максимальный размер привата в конфигурации превышает допустимый предел. Значение должно быть не больше <red>2147483647<gray>. Обратитесь к администратору сервера."
  region-already-exists: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Регион с таким именем уже существует."
  too-many-regions: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>У вас слишком много регионов, удалите один из них перед тем как заприватить новый."
  region-too-large: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Размер региона слишком большой. Максимальный размер: <green>%max%<gray>, ваш размер: <red>%current%<gray>."
  overlapping-others-region: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Регион не создан. Он перекрывает чужой регион."
  claim-only-inside-existing: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Вы можете приватить только внутри своих регионов."
  region-created: "<dark_gray>[<green><b>!<reset><dark_gray>] <gray>Регион <green>%id%<gray> создан."
  region-creation-error: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Произошла ошибка при привате региона <red>%id%<gray>."
  only-cuboid-selection-allowed: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Вы можете использовать только кубическую территорию."
  no-selection-made: "<dark_gray>[<yellow><b>!<reset><dark_gray>] <gray>Сначала выделите территорию. Используйте WorldEdit для выделения: <green>https://worldedit.enginehub.org<gray>."
  region-expanded-vertically: "<dark_gray>[<green><b>!<reset><dark_gray>] <gray>Регион автоматически расширен по вертикали."
  claim-too-large: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Вы не можете заприватить такой большой регион"
  claim-your-limit: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Ваш лимит: <dark_gray>[<green>%limit%<dark_gray>]. <gray>Размер выделения: <dark_gray>[<red>%size%<dark_gray>].<reset>"
  claim-too-small: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Вы не можете заприватить такой маленький регион."
  claim-min-volume: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Минимальный размер: <green>%limit%<gray>, вы попытались заприватить: <red>%size%<gray>."
  claim-too-narrow: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Вы не можете заприватить такой узкий регион."
  claim-min-width: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Минимальная ширина: <green>%limit%<gray>, вы попытались заприватить: <red>%size%<gray>."
  claim-too-low: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Вы не можете заприватить такой низкий регион."
  claim-min-height: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Минимальная высота: <green>%limit%<gray>, вы попытались заприватить: <red>%size%<gray>."
  admin-no-permission: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Недостаточно прав."
  admin-help-reload: "<dark_gray>[<yellow><b>!<reset><dark_gray>] <gray><green>wgex reload<gray> - перезагрузить конфиг."
  admin-help-search: "<dark_gray>[<yellow><b>!<reset><dark_gray>] <gray><green>wgex search<gray> - ищет регионы в выделенной области."
  admin-help-setflag: "<dark_gray>[<yellow><b>!<reset><dark_gray>] <gray><green>wgex setflag {world} {flag} {value}<gray> - устанавливает флаг <green>{flag}<gray> со значением <green>{value}<gray> на все регионы в мире <green>{world}<gray>."
  admin-help-removeowner: "<dark_gray>[<yellow><b>!<reset><dark_gray>] <gray><green>wgex removeowner {name}<gray> - удаляет игрока из списков владельцев всех регионов."
  admin-help-removemember: "<dark_gray>[<yellow><b>!<reset><dark_gray>] <gray><green>wgex removemember {name}<gray> - удаляет игрока из списков членов всех регионов."
  admin-config-reloaded: "<dark_gray>[<green><b>!<reset><dark_gray>] <gray>Конфиг перезагружен."
  admin-search-none: "<dark_gray>[<yellow><b>!<reset><dark_gray>] <gray>Регионов, пересекающихся с выделенной зоной, не найдено."
  admin-search-found: "<dark_gray>[<green><b>!<reset><dark_gray>] <gray>Найдены регионы, пересекающиеся с выделенной зоной: <green>%regions%<gray>."
  admin-search-no-selection: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Сначала выделите зону поиска."
  admin-world-not-found: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Мир не найден."
  admin-flag-not-found: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Флаг не найден."
  admin-flags-set: "<dark_gray>[<green><b>!<reset><dark_gray>] <gray>Флаги установлены."
  admin-flag-invalid-format: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Неправильный формат флага <red>%flag%<gray>: <red>%error%<gray>."
  admin-player-removed-from-all-regions: "<dark_gray>[<green><b>!<reset><dark_gray>] <gray>Игрок удалён из списков <green>%group%<gray> всех регионов."
  admin-region-group-owners: "<green>владельцев<gray>"
  admin-region-group-members: "<green>участников<gray>"
  chorus-fruit-denied: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Вы не можете использовать хорус в этом регионе."
  restricted-command-denied: "<dark_gray>[<red><b>!<reset><dark_gray>] <gray>Вы не можете использовать эту команду в чужом регионе."
  wand-given: "<dark_gray>[<green><b>!<reset><dark_gray>] <gray>Выдана вещь для выделения территории."
  wand-display-name: "<dark_gray>[<yellow><b>!<reset><dark_gray>] <gray>Инструмент выделения"